title: "Mathias Berg"
logo: /assets/img/cara_cropped.png
description: "Industrial Engineer specializing in Data Analysis, Science, and Engineering. Experienced in BI, Data Warehousing, Python and SQL."
show_downloads: false
#theme: jekyll-theme-cayman  # Changed to a more visually engaging theme
theme: jekyll-theme-minimal

# Social Links
social_links:
  github: "https://github.com/mbergr"
  linkedin: "https://linkedin.com/in/your-profile"
  email: "your-email@example.com"

# Navigation items
nav:
  - title: "About"
    url: "/#about"
  - title: "Projects"
    url: "/#projects"
  - title: "Contact"
    url: "/#contact"

# Styling Enhancements
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom CSS for more control over the look
#custom_css:
#  - /assets/css/custom.css
