title: Mathias Berg
logo: /assets/img/cara_cropped.png
description: Engineer looking for a first job experience in Data Analysis, Science and/or Engineering.
show_downloads: false
theme: jekyll-theme-minimal
